"""create_practice_sessions  migration

Revision ID: ab24c2af5605
Revises: fb66b2e5b723
Create Date: 2025-04-16 11:38:23.143523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab24c2af5605'
down_revision: Union[str, None] = 'fb66b2e5b723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
