"""Initial migration

Revision ID: ede56dadacd2
Revises: c592a26bcdfb
Create Date: 2025-03-29 13:55:17.915354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede56dadacd2'
down_revision = 'c592a26bcdfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 