"""setup migration

Revision ID: a283df49ee99
Revises: 5b5566759f8d
Create Date: 2025-03-29 15:27:32.962599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a283df49ee99'
down_revision = '5b5566759f8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careerprofile', sa.Column('strengths', sa.JSON(), nullable=True))
    op.add_column('careerprofile', sa.Column('weaknesses', sa.JSON(), nullable=True))
    op.add_column('careerprofile', sa.Column('skill_gaps', sa.JSON(), nullable=True))
    op.add_column('careerprofile', sa.Column('recommended_career_paths', sa.JSON(), nullable=True))
    op.add_column('careerprofile', sa.Column('recommended_skills', sa.JSON(), nullable=True))
    op.add_column('careerprofile', sa.Column('recommended_actions', sa.JSON(), nullable=True))
    op.add_column('careerprofile', sa.Column('embedding_vector', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('experiences', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('education', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('career_goals', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('preferred_industries', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferred_industries')
    op.drop_column('user', 'career_goals')
    op.drop_column('user', 'education')
    op.drop_column('user', 'experiences')
    op.drop_column('user', 'skills')
    op.drop_column('careerprofile', 'embedding_vector')
    op.drop_column('careerprofile', 'recommended_actions')
    op.drop_column('careerprofile', 'recommended_skills')
    op.drop_column('careerprofile', 'recommended_career_paths')
    op.drop_column('careerprofile', 'skill_gaps')
    op.drop_column('careerprofile', 'weaknesses')
    op.drop_column('careerprofile', 'strengths')
    # ### end Alembic commands ### 