"""Initial migration

Revision ID: 5b5566759f8d
Revises: ede56dadacd2
Create Date: 2025-03-29 13:57:01.573150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5566759f8d'
down_revision = 'ede56dadacd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 