"""initial

Revision ID: e66417bfa9d5
Revises: 
Create Date: 2025-04-14 23:16:38.644897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66417bfa9d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('personal_info', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('experiences', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('skill_gaps', sa.JSON(), nullable=True),
    sa.Column('career_paths', sa.JSON(), nullable=True),
    sa.Column('recommended_skills', sa.JSON(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('analysis_summary', sa.JSON(), nullable=True),
    sa.Column('career_matches', sa.JSON(), nullable=True),
    sa.Column('preferred_industries', sa.JSON(), nullable=True),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.JSON(), nullable=True),
    sa.Column('completeness', sa.JSON(), nullable=True),
    sa.Column('formatting', sa.JSON(), nullable=True),
    sa.Column('section_scores', sa.JSON(), nullable=True),
    sa.Column('language_quality', sa.JSON(), nullable=True),
    sa.Column('ats_compatibility', sa.JSON(), nullable=True),
    sa.Column('detailed_metrics', sa.JSON(), nullable=True),
    sa.Column('improvement_priority', sa.JSON(), nullable=True),
    sa.Column('analysis_status', sa.String(length=50), nullable=True),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_id'), 'cv', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_id'), table_name='cv')
    op.drop_table('cv')
    # ### end Alembic commands ###
